/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.waterwolfies.silk_spawner;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

class PluginTest {
    
}
